### ISSUE TITLE
Add ability to show rpm info?

### ISSUE THREAD

**Issue by reidrivenburgh** [mlichvar/rpmreaper#3]
I like rpmreaper, but I find myself doing "rpm -qi <package>" a lot in another terminal, since I don't recognize half the packages on my system.  It would be nice if rpmreaper could show that output automatically.  Thank you.

**Comment by mlichvar** [comment]
The key `i` should show the info together with a file list. Does it not work for you?

**Comment by reidrivenburgh** [comment]
Ahh, I missed that.  It actually doesn't work for me, but I assume it's an issue with PAGER.  It just flashes quickly, redisplaying the package list.  Separate problem.  Thank you.
